products = [
    {
        "id": 1,
        "name": "Wireless Mouse",
        "category": "Electronics",
        "price": 25.99,
        "stock": 120,
        "rating": 4.5,
        "is_available": True,
    },
    {
        "id": 2,
        "name": "Gaming Keyboard",
        "category": "Electronics",
        "price": 79.99,
        "stock": 45,
        "rating": 4.7,
        "is_available": True,
    },
    {
        "id": 3,
        "name": "Running Shoes",
        "category": "Fashion",
        "price": 59.50,
        "stock": 30,
        "rating": 4.3,
        "is_available": True,
    },
    {
        "id": 4,
        "name": "Coffee Mug",
        "category": "Home & Kitchen",
        "price": 12.99,
        "stock": 200,
        "rating": 4.1,
        "is_available": True,
    },
    {
        "id": 5,
        "name": "Office Chair",
        "category": "Furniture",
        "price": 149.99,
        "stock": 10,
        "rating": 4.6,
        "is_available": False,
    },
]